// Curated list for the payout application bank picker. Nigeria has 20+
// commercial banks and several hundred CBN-licensed microfinance banks —
// hardcoding every MFB would bloat the dropdown and go stale, so this
// covers the commercial banks plus the microfinance banks realtors are most
// likely to actually bank with. "Other" reveals a free-text field on the
// form for anything not listed.
export const NIGERIAN_BANKS = [
  // Commercial banks
  'Access Bank',
  'Citibank Nigeria',
  'Ecobank Nigeria',
  'Fidelity Bank',
  'First Bank of Nigeria',
  'First City Monument Bank (FCMB)',
  'Globus Bank',
  'Guaranty Trust Bank (GTBank)',
  'Heritage Bank',
  'Keystone Bank',
  'Optimus Bank',
  'Parallex Bank',
  'Polaris Bank',
  'Premium Trust Bank',
  'Providus Bank',
  'Signature Bank',
  'Stanbic IBTC Bank',
  'Standard Chartered Bank',
  'Sterling Bank',
  'SunTrust Bank',
  'Titan Trust Bank',
  'Union Bank of Nigeria',
  'United Bank for Africa (UBA)',
  'Unity Bank',
  'Wema Bank',
  'Zenith Bank',
  // Digital / microfinance-licensed banks
  'Kuda Microfinance Bank',
  'Moniepoint Microfinance Bank',
  'OPay (Paycom)',
  'PalmPay',
  'VFD Microfinance Bank',
  'Rubies Microfinance Bank',
  'Sparkle Microfinance Bank',
  'Mint Finex MFB',
  'Fairmoney Microfinance Bank',
  'Carbon Microfinance Bank',
  // Established microfinance banks
  'AB Microfinance Bank',
  'Accion Microfinance Bank',
  'Baobab Microfinance Bank',
  'Fina Trust Microfinance Bank',
  'Grooming Microfinance Bank',
  'Hasal Microfinance Bank',
  'Infinity Microfinance Bank',
  'LAPO Microfinance Bank',
  'Mainstreet Microfinance Bank',
  'NPF Microfinance Bank',
  'Peace Microfinance Bank',
  'Personal Trust Microfinance Bank',
  'Renmoney Microfinance Bank',
  'Sagegrey Microfinance Bank',
  'Seed Capital Microfinance Bank',
  'Boctrust Microfinance Bank',
  'Other',
] as const;
